### ISSUE TITLE
NetMatch* freezes on Cytoscape 3.8.0

### ISSUE THREAD

**Issue by mikekucera** [fabiorinnone/NetMatchStar#23]
Original bug report here: https://cytoscape.atlassian.net/browse/CSD-253

There were some major changes to the network renderer in Cytoscape 3.8.0, which broke the network image generation in NetMatch*. This will have to be fixed in the NetMatch* app. I will provide a pull request soon.

**Comment by mikekucera** [comment]
Pull request: https://github.com/fabiorinnone/NetMatchStar/pull/24

**Comment by fabiorinnone** [comment]
Issue resolved. I'm going to publish new release v 3.2.1.
